[build]
  publish = "src"
  functions = "netlify/functions"
  command = "npm install"

[dev]
  publish = "src"
  functions = "netlify/functions"
  port = 8888
  timeout = 120

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
